Treino.Web/Areas/StudioGhibli/Controllers/PessoasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Treino.API.Controllers.V1;
using Treino.ViewModels;

namespace Treino.Web.Controllers
{
    [Area("StudioGhibli")]
    public class PessoasController : Controller
    {
        PessoasApiController _pessoasApiController;

        public PessoasController()
        {
            _pessoasApiController = new PessoasApiController();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            try
            {
                var pessoaObjResult = await _pessoasApiController.Listar();
                if (pessoaObjResult != null)
                {
                    IEnumerable<PessoaModel> listaPessoas = (IEnumerable<PessoaModel>)pessoaObjResult.Value;
                    return View("Lista", listaPessoas);
                }
                return View("Lista", null);
            }
            catch (Exception excessao)
            {
                return NotFound(excessao);
            }
        }

        public async Task<IActionResult> ObtemPessoa(string id)
        {
            try
            {
                var pessoaObjResult = await _pessoasApiController.ListaPessoa(id);
                if (pessoaObjResult != null)
                {
                    PessoaModel pessoa = (PessoaModel)pessoaObjResult.Value;
                    return View("Obtem", pessoa);
                }
                return View("Obtem", null);
            }
            catch (Exception excessao)
            {
                return NotFound(excessao);
            }
        }
    }
}

Treino.Web/Areas/StudioGhibli/Views/Pessoas/Lista.cshtml
@model IEnumerable<Treino.ViewModels.PessoaModel>

@{
    ViewData["Title"] = "Pessoa";
}
<div class="position-relative overflow-hidden text-center bg-light">
    <div class="col-md-12 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal"> Api Studio Ghibi - Pessoas </h1>
        <p class="lead font-weight-normal">Requisição para Listar todos as Pessoas do Studio Ghibi.</p>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
</div>

@foreach (var pessoa in Model)
{
    <div class="w-100 my-md-3 pl-md-3">
        <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <div class="my-3 py-3">
                <h2 class="display-5">@pessoa.name</h2>
                <p class="small">Id: @pessoa.id</p>
                <p class="lead">@pessoa.gender | Idade: @pessoa.age </p>
                <p class="lead">Cor dos Olhos @pessoa.eye_color | Cor do Cabelo: @pessoa.hair_color</p>
                <p class="small">Url para essa requisição: @pessoa.url</p>

                <a asp-controller="Pessoas" asp-action="ObtemPessoa" asp-route-id="@pessoa.id" class="btn btn-info">Detalhes</a>

            </div>
            <div class="bg-light box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
                <h3 class="text-dark">Participação em Filmes </h3>
                @foreach (var filmesRealizados in pessoa.filmesModel)
                {
                    <h4 class="display-5">@filmesRealizados.title</h4>
                    <p class="lead">@filmesRealizados.description</p>
                    <p class="lead">@filmesRealizados.locations</p>
                    <p class="lead">@filmesRealizados.producer</p>
                    @*@filme.id</th>
                    @filme.director</th>
                    @filme.original_title</th>
                    @filme.original_title_romanised
                    @filme.people</th>
                    @filme.release_date</th>
                    </th>*@

                }
            </div>
        </div>
    </div>
}

Treino.Web/Areas/StudioGhibli/Views/Pessoas/Obtem.cshtml
@model Treino.ViewModels.PessoaModel

@{
    ViewData["Title"] = "Pessoa Descrição";
}
<div>
    <a asp-action="Lista">Retorna a Lista</a>
</div>
<header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
    <div class="text-center my-5">
        <img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="...">
        <h1 class="text-white fs-3 fw-bolder">@Model.name</h1>
        <p class="text-white-50 mb-0">@ViewData["Title"]</p>
    </div>
</header>

<section class="pt-4">
    <div class="container px-lg-5">
        <!-- Page Features-->
        <div class="row gx-lg-5">
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class=""></i></div>
                        <h2 class="fs-4 fw-bold">Nome do Ator</h2>
                        <p class="mb-0">@Model.name</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-cloud-download"></i></div>
                        <h2 class="fs-4 fw-bold">ID</h2>
                        <p class="mb-0">@Model.id</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-card-heading"></i></div>
                        <h2 class="fs-4 fw-bold">Genêro</h2>
                        <p class="mb-0">@Model.gender</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-bootstrap"></i></div>
                        <h2 class="fs-4 fw-bold">Idade</h2>
                        <p class="mb-0">@Model.age</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-code"></i></div>
                        <h2 class="fs-4 fw-bold">Cor dos Olhos</h2>
                        <p class="mb-0">@Model.eye_color</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <h2 class="fs-4 fw-bold">Cor dos Cabelos</h2>
                        <p class="mb-0">@Model.hair_color</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <h2 class="fs-4 fw-bold">Filmes estreados</h2>
                        @foreach (var filme in Model.filmesModel)
                        {
                            <p class="mb-0">@filme.id</p>
                            @*<p class="mb-0">@filme.locations</p>*@
                            <p class="mb-0">@filme.description</p>
                            <p class="mb-0">@filme.director</p>
                            <p class="mb-0">@filme.original_title</p>
                            <p class="mb-0">@filme.original_title_romanised</p>
                            <p class="mb-0">@filme.people</p>
                            <p class="mb-0">@filme.producer</p>
                            <p class="mb-0">@filme.release_date</p>
                            <p class="mb-0">@filme.title</p>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                        <h2 class="fs-4 fw-bold">Especie</h2>                      
                            <p class="mb-0">@Model.especieModel.name</p>
                            <p class="mb-0">@Model.especieModel.classification</p>
                            <p class="mb-0">@Model.especieModel.eye_colors</p>
                            <p class="mb-0">@Model.especieModel.url</p>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@*
    <div>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.species)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.url)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.url)
            </dd>
        </dl>
    </div>
    <div>
*@